name: Build
on:
  push:
    branches:
      - mdb.master
  pull_request:
    branches:
      - mdb.master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          build-cache: true

      - name: Run xmake build
        run: xmake build
